import { VariantProps, cva } from "class-variance-authority";
import React, { ReactNode } from "react";
import { cn } from "utils/helpers/cn";

const textElementData = [
  { id: 1, Element: "p" },
  { id: 2, Element: "h1" },
  { id: 3, Element: "h2" },
  { id: 4, Element: "h3" },
  { id: 5, Element: "h4" },
  { id: 6, Element: "h5" },
  { id: 7, Element: "h6" },
  { id: 8, Element: "label" },
  { id: 9, Element: "span" },
];

interface TextProps extends VariantProps<typeof textVariants> {
  className?: string;
  as: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "label" | "span";
  text?: string;
  children?: ReactNode;
  onClick?: () => void;
}

export function Text({
  as,
  text,
  children,
  className,
  variant,
  color,
  onClick,
  size,
  weight,
  ...props
}: TextProps) {
  let TextElement: JSX.Element | null = null;

  textElementData?.forEach(({ Element }) => {
    if (Element === as) {
      TextElement = (
        <Element
          onClick={onClick}
          className={cn(
            textVariants({ variant, color, size, weight, className })
          )}
          {...props}
        >
          {text && text}
          {children && children}
        </Element>
      );
    }
  });
  return TextElement;
}

const textVariants = cva("", {
  variants: {
    size: {
      xs: "text-[0.75rem]", // 12px
      sm: "text-[0.875]rem", // 14px
      md: "text-[1rem]", // 16px
      lg: "text-[1.125rem]", // 18px
      xl: "text-[1.375rem]", // 22px
      "2xl": "text-[1.625rem]", // 26px
      "3xl": "text-[3.75rem]", // 60px
    },
    weight: {
      regular: "font-normal",
      medium: "font-medium",
      semiBold: "font-semibold",
      bold: "font-bold",
    },
    color: {
      black: "text-black",
      white: "text-white",
      "dark-blue": "text-dark-blue",
      "nile-blue": "text-nile-blue",
      "purple-blue": "text-purple-blue",
      "cold-purple": "text-cold-purple",
      "dark-grey": "text-dark-grey",
      "french-grey": "text-french-grey",
      "soft-peach": "text-soft-peach",
      "santa-grey": "text-santa-grey",
      transparent: "text-transparent",
    },
    variant: {
      "xs-regular-black": "text-[0.75rem] font-normal text-black",
      "xs-regular-white": "text-[0.75rem] font-normal text-white",
      "xs-regular-dark-blue": "text-[0.75rem] font-normal text-dark-blue",
      "xs-regular-nile-blue": "text-[0.75rem] font-normal text-nile-blue",
      "xs-regular-purple-blue": "text-[0.75rem] font-normal text-purple-blue",
      "xs-regular-cold-purple": "text-[0.75rem] font-normal text-cold-purple",
      "xs-regular-dark-grey": "text-[0.75rem] font-normal text-dark-grey",
      "xs-regular-french-grey": "text-[0.75rem] font-normal text-french-grey",
      "xs-regular-soft-peach": "text-[0.75rem] font-normal text-soft-peach",
      "xs-regular-santa-grey": "text-[0.75rem] font-normal text-santa-grey",
      "sm-regular-black": "text-[0.875rem] font-normal text-black",
      "sm-regular-white": "text-[0.875rem] font-normal text-white",
      "sm-regular-dark-blue": "text-[0.875rem] font-normal text-dark-blue",
      "sm-regular-nile-blue": "text-[0.875rem] font-normal text-nile-blue",
      "sm-regular-purple-blue": "text-[0.875rem] font-normal text-purple-blue",
      "sm-regular-cold-purple": "text-[0.875rem] font-normal text-cold-purple",
      "sm-regular-dark-grey": "text-[0.875rem] font-normal text-dark-grey",
      "sm-regular-french-grey": "text-[0.875rem] font-normal text-french-grey",
      "sm-regular-soft-peach": "text-[0.875rem] font-normal text-soft-peach",
      "sm-regular-santa-grey": "text-[0.875rem] font-normal text-santa-grey",
      "md-regular-black": "text-[1rem] font-normal text-black",
      "md-regular-white": "text-[1rem] font-normal text-white",
      "md-regular-dark-blue": "text-[1rem] font-normal text-dark-blue",
      "md-regular-nile-blue": "text-[1rem] font-normal text-nile-blue",
      "md-regular-purple-blue": "text-[1rem] font-normal text-purple-blue",
      "md-regular-cold-purple": "text-[1rem] font-normal text-cold-purple",
      "md-regular-dark-grey": "text-[1rem] font-normal text-dark-grey",
      "md-regular-french-grey": "text-[1rem] font-normal text-french-grey",
      "md-regular-soft-peach": "text-[1rem] font-normal text-soft-peach",
      "md-regular-santa-grey": "text-[1rem] font-normal text-santa-grey",
      "lg-regular-black": "text-[1.125rem] font-normal text-black",
      "lg-regular-white": "text-[1.125rem] font-normal text-white",
      "lg-regular-dark-blue": "text-[1.125rem] font-normal text-dark-blue",
      "lg-regular-nile-blue": "text-[1.125rem] font-normal text-nile-blue",
      "lg-regular-purple-blue": "text-[1.125rem] font-normal text-purple-blue",
      "lg-regular-cold-purple": "text-[1.125rem] font-normal text-cold-purple",
      "lg-regular-dark-grey": "text-[1.125rem] font-normal text-dark-grey",
      "lg-regular-french-grey": "text-[1.125rem] font-normal text-french-grey",
      "lg-regular-soft-peach": "text-[1.125rem] font-normal text-soft-peach",
      "lg-regular-santa-grey": "text-[1.125rem] font-normal text-santa-grey",
      "xl-regular-black": "text-[1.375rem] font-normal text-black",
      "xl-regular-white": "text-[1.375rem] font-normal text-white",
      "xl-regular-dark-blue": "text-[1.375rem] font-normal text-dark-blue",
      "xl-regular-nile-blue": "text-[1.375rem] font-normal text-nile-blue",
      "xl-regular-purple-blue": "text-[1.375rem] font-normal text-purple-blue",
      "xl-regular-cold-purple": "text-[1.375rem] font-normal text-cold-purple",
      "xl-regular-dark-grey": "text-[1.375rem] font-normal text-dark-grey",
      "xl-regular-french-grey": "text-[1.375rem] font-normal text-french-grey",
      "xl-regular-soft-peach": "text-[1.375rem] font-normal text-soft-peach",
      "xl-regular-santa-grey": "text-[1.375rem] font-normal text-santa-grey",
      "2xl-regular-black": "text-[1.625rem] font-normal text-black",
      "2xl-regular-white": "text-[1.625rem] font-normal text-white",
      "2xl-regular-dark-blue": "text-[1.625rem] font-normal text-dark-blue",
      "2xl-regular-nile-blue": "text-[1.625rem] font-normal text-nile-blue",
      "2xl-regular-purple-blue": "text-[1.625rem] font-normal text-purple-blue",
      "2xl-regular-cold-purple": "text-[1.625rem] font-normal text-cold-purple",
      "2xl-regular-dark-grey": "text-[1.625rem] font-normal text-dark-grey",
      "2xl-regular-french-grey": "text-[1.625rem] font-normal text-french-grey",
      "2xl-regular-soft-peach": "text-[1.625rem] font-normal text-soft-peach",
      "2xl-regular-santa-grey": "text-[1.625rem] font-normal text-santa-grey",
      "3xl-regular-black": "text-[3.75rem] font-normal text-black",
      "3xl-regular-white": "text-[3.75rem] font-normal text-white",
      "3xl-regular-dark-blue": "text-[3.75rem] font-normal text-dark-blue",
      "3xl-regular-nile-blue": "text-[3.75rem] font-normal text-nile-blue",
      "3xl-regular-purple-blue": "text-[3.75rem] font-normal text-purple-blue",
      "3xl-regular-cold-purple": "text-[3.75rem] font-normal text-cold-purple",
      "3xl-regular-dark-grey": "text-[3.75rem] font-normal text-dark-grey",
      "3xl-regular-french-grey": "text-[3.75rem] font-normal text-french-grey",
      "3xl-regular-soft-peach": "text-[3.75rem] font-normal text-soft-peach",
      "3xl-regular-santa-grey": "text-[3.75rem] font-normal text-santa-grey",
      "sm-medium-black": "text-[0.875rem] font-medium text-black",
      "sm-medium-white": "text-[0.875rem] font-medium text-white",
      "sm-medium-dark-blue": "text-[0.875rem] font-medium text-dark-blue",
      "sm-medium-nile-blue": "text-[0.875rem] font-medium text-nile-blue",
      "sm-medium-purple-blue": "text-[0.875rem] font-medium text-purple-blue",
      "sm-medium-cold-purple": "text-[0.875rem] font-medium text-cold-purple",
      "sm-medium-dark-grey": "text-[0.875rem] font-medium text-dark-grey",
      "sm-medium-french-grey": "text-[0.875rem] font-medium text-french-grey",
      "sm-medium-soft-peach": "text-[0.875rem] font-medium text-soft-peach",
      "sm-medium-santa-grey": "text-[0.875rem] font-medium text-santa-grey",
      "md-medium-black": "text-[1rem] font-medium text-black",
      "md-medium-white": "text-[1rem] font-medium text-white",
      "md-medium-dark-blue": "text-[1rem] font-medium text-dark-blue",
      "md-medium-nile-blue": "text-[1rem] font-medium text-nile-blue",
      "md-medium-purple-blue": "text-[1rem] font-medium text-purple-blue",
      "md-medium-cold-purple": "text-[1rem] font-medium text-cold-purple",
      "md-medium-dark-grey": "text-[1rem] font-medium text-dark-grey",
      "md-medium-french-grey": "text-[1rem] font-medium text-french-grey",
      "md-medium-soft-peach": "text-[1rem] font-medium text-soft-peach",
      "md-medium-santa-grey": "text-[1rem] font-medium text-santa-grey",
      "lg-medium-black": "text-[1.125rem] font-medium text-black",
      "lg-medium-white": "text-[1.125rem] font-medium text-white",
      "lg-medium-dark-blue": "text-[1.125rem] font-medium text-dark-blue",
      "lg-medium-nile-blue": "text-[1.125rem] font-medium text-nile-blue",
      "lg-medium-purple-blue": "text-[1.125rem] font-medium text-purple-blue",
      "lg-medium-cold-purple": "text-[1.125rem] font-medium text-cold-purple",
      "lg-medium-dark-grey": "text-[1.125rem] font-medium text-dark-grey",
      "lg-medium-french-grey": "text-[1.125rem] font-medium text-french-grey",
      "lg-medium-soft-peach": "text-[1.125rem] font-medium text-soft-peach",
      "lg-medium-santa-grey": "text-[1.125rem] font-medium text-santa-grey",
      "xl-medium-black": "text-[1.375rem] font-medium text-black",
      "xl-medium-white": "text-[1.375rem] font-medium text-white",
      "xl-medium-dark-blue": "text-[1.375rem] font-medium text-dark-blue",
      "xl-medium-nile-blue": "text-[1.375rem] font-medium text-nile-blue",
      "xl-medium-purple-blue": "text-[1.375rem] font-medium text-purple-blue",
      "xl-medium-cold-purple": "text-[1.375rem] font-medium text-cold-purple",
      "xl-medium-dark-grey": "text-[1.375rem] font-medium text-dark-grey",
      "xl-medium-french-grey": "text-[1.375rem] font-medium text-french-grey",
      "xl-medium-soft-peach": "text-[1.375rem] font-medium text-soft-peach",
      "xl-medium-santa-grey": "text-[1.375rem] font-medium text-santa-grey",
      "2xl-medium-black": "text-[1.625rem] font-medium text-black",
      "2xl-medium-white": "text-[1.625rem] font-medium text-white",
      "2xl-medium-dark-blue": "text-[1.625rem] font-medium text-dark-blue",
      "2xl-medium-nile-blue": "text-[1.625rem] font-medium text-nile-blue",
      "2xl-medium-purple-blue": "text-[1.625rem] font-medium text-purple-blue",
      "2xl-medium-cold-purple": "text-[1.625rem] font-medium text-cold-purple",
      "2xl-medium-dark-grey": "text-[1.625rem] font-medium text-dark-grey",
      "2xl-medium-french-grey": "text-[1.625rem] font-medium text-french-grey",
      "2xl-medium-soft-peach": "text-[1.625rem] font-medium text-soft-peach",
      "2xl-medium-santa-grey": "text-[1.625rem] font-medium text-santa-grey",
      "3xl-medium-black": "text-[3.75rem] font-medium text-black",
      "3xl-medium-white": "text-[3.75rem] font-medium text-white",
      "3xl-medium-dark-blue": "text-[3.75rem] font-medium text-dark-blue",
      "3xl-medium-nile-blue": "text-[3.75rem] font-medium text-nile-blue",
      "3xl-medium-purple-blue": "text-[3.75rem] font-medium text-purple-blue",
      "3xl-medium-cold-purple": "text-[3.75rem] font-medium text-cold-purple",
      "3xl-medium-dark-grey": "text-[3.75rem] font-medium text-dark-grey",
      "3xl-medium-french-grey": "text-[3.75rem] font-medium text-french-grey",
      "3xl-medium-soft-peach": "text-[3.75rem] font-medium text-soft-peach",
      "3xl-medium-santa-grey": "text-[3.75rem] font-medium text-santa-grey",
      "xs-semibold-black": "text-[0.75rem] font-semibold text-black",
      "xs-semibold-white": "text-[0.75rem] font-semibold text-white",
      "xs-semibold-dark-blue": "text-[0.75rem] font-semibold text-dark-blue",
      "xs-semibold-nile-blue": "text-[0.75rem] font-semibold text-nile-blue",
      "xs-semibold-purple-blue":
        "text-[0.75rem] font-semibold text-purple-blue",
      "xs-semibold-cold-purple":
        "text-[0.75rem] font-semibold text-cold-purple",
      "xs-semibold-dark-grey": "text-[0.75rem] font-semibold text-dark-grey",
      "xs-semibold-french-grey":
        "text-[0.75rem] font-semibold text-french-grey",
      "xs-semibold-soft-peach": "text-[0.75rem] font-semibold text-soft-peach",
      "xs-semibold-santa-grey": "text-[0.75rem] font-semibold text-santa-grey",
      "sm-semibold-black": "text-[0.875rem] font-semibold text-black",
      "sm-semibold-white": "text-[0.875rem] font-semibold text-white",
      "sm-semibold-dark-blue": "text-[0.875rem] font-semibold text-dark-blue",
      "sm-semibold-nile-blue": "text-[0.875rem] font-semibold text-nile-blue",
      "sm-semibold-purple-blue":
        "text-[0.875rem] font-semibold text-purple-blue",
      "sm-semibold-cold-purple":
        "text-[0.875rem] font-semibold text-cold-purple",
      "sm-semibold-dark-grey": "text-[0.875rem] font-semibold text-dark-grey",
      "sm-semibold-french-grey":
        "text-[0.875rem] font-semibold text-french-grey",
      "sm-semibold-soft-peach": "text-[0.875rem] font-semibold text-soft-peach",
      "sm-semibold-santa-grey": "text-[0.875rem] font-semibold text-santa-grey",
      "md-semibold-black": "text-[1rem] font-semibold text-black",
      "md-semibold-white": "text-[1rem] font-semibold text-white",
      "md-semibold-dark-blue": "text-[1rem] font-semibold text-dark-blue",
      "md-semibold-nile-blue": "text-[1rem] font-semibold text-nile-blue",
      "md-semibold-purple-blue": "text-[1rem] font-semibold text-purple-blue",
      "md-semibold-cold-purple": "text-[1rem] font-semibold text-cold-purple",
      "md-semibold-dark-grey": "text-[1rem] font-semibold text-dark-grey",
      "md-semibold-french-grey": "text-[1rem] font-semibold text-french-grey",
      "md-semibold-soft-peach": "text-[1rem] font-semibold text-soft-peach",
      "md-semibold-santa-grey": "text-[1rem] font-semibold text-santa-grey",
      "lg-semibold-black": "text-[1.125rem] font-semibold text-black",
      "lg-semibold-white": "text-[1.125rem] font-semibold text-white",
      "lg-semibold-dark-blue": "text-[1.125rem] font-semibold text-dark-blue",
      "lg-semibold-nile-blue": "text-[1.125rem] font-semibold text-nile-blue",
      "lg-semibold-purple-blue":
        "text-[1.125rem] font-semibold text-purple-blue",
      "lg-semibold-cold-purple":
        "text-[1.125rem] font-semibold text-cold-purple",
      "lg-semibold-dark-grey": "text-[1.125rem] font-semibold text-dark-grey",
      "lg-semibold-french-grey":
        "text-[1.125rem] font-semibold text-french-grey",
      "lg-semibold-soft-peach": "text-[1.125rem] font-semibold text-soft-peach",
      "lg-semibold-santa-grey": "text-[1.125rem] font-semibold text-santa-grey",
      "xl-semibold-black": "text-[1.375rem] font-semibold text-black",
      "xl-semibold-white": "text-[1.375rem] font-semibold text-white",
      "xl-semibold-dark-blue": "text-[1.375rem] font-semibold text-dark-blue",
      "xl-semibold-nile-blue": "text-[1.375rem] font-semibold text-nile-blue",
      "xl-semibold-purple-blue":
        "text-[1.375rem] font-semibold text-purple-blue",
      "xl-semibold-cold-purple":
        "text-[1.375rem] font-semibold text-cold-purple",
      "xl-semibold-dark-grey": "text-[1.375rem] font-semibold text-dark-grey",
      "xl-semibold-french-grey":
        "text-[1.375rem] font-semibold text-french-grey",
      "xl-semibold-soft-peach": "text-[1.375rem] font-semibold text-soft-peach",
      "xl-semibold-santa-grey": "text-[1.375rem] font-semibold text-santa-grey",
      "2xl-semibold-black": "text-[1.625rem] font-semibold text-black",
      "2xl-semibold-white": "text-[1.625rem] font-semibold text-white",
      "2xl-semibold-dark-blue": "text-[1.625rem] font-semibold text-dark-blue",
      "2xl-semibold-nile-blue": "text-[1.625rem] font-semibold text-nile-blue",
      "2xl-semibold-purple-blue":
        "text-[1.625rem] font-semibold text-purple-blue",
      "2xl-semibold-cold-purple":
        "text-[1.625rem] font-semibold text-cold-purple",
      "2xl-semibold-dark-grey": "text-[1.625rem] font-semibold text-dark-grey",
      "2xl-semibold-french-grey":
        "text-[1.625rem] font-semibold text-french-grey",
      "2xl-semibold-soft-peach":
        "text-[1.625rem] font-semibold text-soft-peach",
      "2xl-semibold-santa-grey":
        "text-[1.625rem] font-semibold text-santa-grey",
      "3xl-semibold-black": "text-[3.75rem] font-semibold text-black",
      "3xl-semibold-white": "text-[3.75rem] font-semibold text-white",
      "3xl-semibold-dark-blue": "text-[3.75rem] font-semibold text-dark-blue",
      "3xl-semibold-nile-blue": "text-[3.75rem] font-semibold text-nile-blue",
      "3xl-semibold-purple-blue":
        "text-[3.75rem] font-semibold text-purple-blue",
      "3xl-semibold-cold-purple":
        "text-[3.75rem] font-semibold text-cold-purple",
      "3xl-semibold-dark-grey": "text-[3.75rem] font-semibold text-dark-grey",
      "3xl-semibold-french-grey":
        "text-[3.75rem] font-semibold text-french-grey",
      "3xl-semibold-soft-peach": "text-[3.75rem] font-semibold text-soft-peach",
      "3xl-semibold-santa-grey": "text-[3.75rem] font-semibold text-santa-grey",
      "xs-bold-black": "text-[0.75rem] font-bold text-black",
      "xs-bold-white": "text-[0.75rem] font-bold text-white",
      "xs-bold-dark-blue": "text-[0.75rem] font-bold text-dark-blue",
      "xs-bold-nile-blue": "text-[0.75rem] font-bold text-nile-blue",
      "xs-bold-purple-blue": "text-[0.75rem] font-bold text-purple-blue",
      "xs-bold-cold-purple": "text-[0.75rem] font-bold text-cold-purple",
      "xs-bold-dark-grey": "text-[0.75rem] font-bold text-dark-grey",
      "xs-bold-french-grey": "text-[0.75rem] font-bold text-french-grey",
      "xs-bold-soft-peach": "text-[0.75rem] font-bold text-soft-peach",
      "xs-bold-santa-grey": "text-[0.75rem] font-bold text-santa-grey",
      "sm-bold-black": "text-[0.875rem] font-bold text-black",
      "sm-bold-white": "text-[0.875rem] font-bold text-white",
      "sm-bold-dark-blue": "text-[0.875rem] font-bold text-dark-blue",
      "sm-bold-nile-blue": "text-[0.875rem] font-bold text-nile-blue",
      "sm-bold-purple-blue": "text-[0.875rem] font-bold text-purple-blue",
      "sm-bold-cold-purple": "text-[0.875rem] font-bold text-cold-purple",
      "sm-bold-dark-grey": "text-[0.875rem] font-bold text-dark-grey",
      "sm-bold-french-grey": "text-[0.875rem] font-bold text-french-grey",
      "sm-bold-soft-peach": "text-[0.875rem] font-bold text-soft-peach",
      "sm-bold-santa-grey": "text-[0.875rem] font-bold text-santa-grey",
      "md-bold-black": "text-[1rem] font-bold text-black",
      "md-bold-white": "text-[1rem] font-bold text-white",
      "md-bold-dark-blue": "text-[1rem] font-bold text-dark-blue",
      "md-bold-nile-blue": "text-[1rem] font-bold text-nile-blue",
      "md-bold-purple-blue": "text-[1rem] font-bold text-purple-blue",
      "md-bold-cold-purple": "text-[1rem] font-bold text-cold-purple",
      "md-bold-dark-grey": "text-[1rem] font-bold text-dark-grey",
      "md-bold-french-grey": "text-[1rem] font-bold text-french-grey",
      "md-bold-soft-peach": "text-[1rem] font-bold text-soft-peach",
      "md-bold-santa-grey": "text-[1rem] font-bold text-santa-grey",
      "lg-bold-black": "text-[1.125rem] font-bold text-black",
      "lg-bold-white": "text-[1.125rem] font-bold text-white",
      "lg-bold-dark-blue": "text-[1.125rem] font-bold text-dark-blue",
      "lg-bold-nile-blue": "text-[1.125rem] font-bold text-nile-blue",
      "lg-bold-purple-blue": "text-[1.125rem] font-bold text-purple-blue",
      "lg-bold-cold-purple": "text-[1.125rem] font-bold text-cold-purple",
      "lg-bold-dark-grey": "text-[1.125rem] font-bold text-dark-grey",
      "lg-bold-french-grey": "text-[1.125rem] font-bold text-french-grey",
      "lg-bold-soft-peach": "text-[1.125rem] font-bold text-soft-peach",
      "lg-bold-santa-grey": "text-[1.125rem] font-bold text-santa-grey",
      "xl-bold-black": "text-[1.375rem] font-bold text-black",
      "xl-bold-white": "text-[1.375rem] font-bold text-white",
      "xl-bold-dark-blue": "text-[1.375rem] font-bold text-dark-blue",
      "xl-bold-nile-blue": "text-[1.375rem] font-bold text-nile-blue",
      "xl-bold-purple-blue": "text-[1.375rem] font-bold text-purple-blue",
      "xl-bold-cold-purple": "text-[1.375rem] font-bold text-cold-purple",
      "xl-bold-dark-grey": "text-[1.375rem] font-bold text-dark-grey",
      "xl-bold-french-grey": "text-[1.375rem] font-bold text-french-grey",
      "xl-bold-soft-peach": "text-[1.375rem] font-bold text-soft-peach",
      "xl-bold-santa-grey": "text-[1.375rem] font-bold text-santa-grey",
      "2xl-bold-black": "text-[1.625rem] font-bold text-black",
      "2xl-bold-white": "text-[1.625rem] font-bold text-white",
      "2xl-bold-dark-blue": "text-[1.625rem] font-bold text-dark-blue",
      "2xl-bold-nile-blue": "text-[1.625rem] font-bold text-nile-blue",
      "2xl-bold-purple-blue": "text-[1.625rem] font-bold text-purple-blue",
      "2xl-bold-cold-purple": "text-[1.625rem] font-bold text-cold-purple",
      "2xl-bold-dark-grey": "text-[1.625rem] font-bold text-dark-grey",
      "2xl-bold-french-grey": "text-[1.625rem] font-bold text-french-grey",
      "2xl-bold-soft-peach": "text-[1.625rem] font-bold text-soft-peach",
      "2xl-bold-santa-grey": "text-[1.625rem] font-bold text-santa-grey",
      "3xl-bold-black": "text-[3.75rem] font-bold text-black",
      "3xl-bold-white": "text-[3.75rem] font-bold text-white",
      "3xl-bold-dark-blue": "text-[3.75rem] font-bold text-dark-blue",
      "3xl-bold-nile-blue": "text-[3.75rem] font-bold text-nile-blue",
      "3xl-bold-purple-blue": "text-[3.75rem] font-bold text-purple-blue",
      "3xl-bold-cold-purple": "text-[3.75rem] font-bold text-cold-purple",
      "3xl-bold-dark-grey": "text-[3.75rem] font-bold text-dark-grey",
      "3xl-bold-french-grey": "text-[3.75rem] font-bold text-french-grey",
      "3xl-bold-soft-peach": "text-[3.75rem] font-bold text-soft-peach",
      "3xl-bold-santa-grey": "text-[3.75rem] font-bold text-santa-grey",
    },
  },
  defaultVariants: {
    variant: "xs-regular-black",
  },
});
