import type { Metadata } from "next";
import { Poppins, DM_Sans } from "next/font/google";
import "../styles/globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${dmSans.className}`}>
        {children}
      </body>
    </html>
  );
}
